# Site settings
title: "笨笨科技"
email: ecobentech@163.com
description: "和笨笨一起呼吸大自然的味道"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Ecobentech
github_username:  Ecobentech

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
